[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Python-Datascience-Handbook"
version = "0.1.0"
dependencies = [
  "ipython"
]

[tool.setuptools]
packages = ["alps"]
